### ISSUE TITLE
Error code moet niet 0 zijn bij fout

### ISSUE THREAD

**Issue by matthijsln** [opengeogroep/vrhDBKconversie#3]
Ik gebruik een script wat kijkt naar de error code van het conversieproces. Deze moet 0 zijn als het goed werkt en ongelijk aan 0 bij een fout.

Bij onderstaande foutmelding verwacht ik een errorcode ongelijk aan 0, maar dat is nu niet zo:

```
File /<dir>/Teksten.shp does not exist.
```

**Comment by ankeur** [comment]
Gebruik je daar een shellscript voor?

**Comment by matthijsln** [comment]
Ja, in een script dat wordt gebruikt in een cronjob. Dat gaat ongeveer als volgt:

```
SHPDIR=...
BACKUPDIR=...
OUTDIR=...
  python3 DBKshape2json.py $SHPDIR $OUTDIR $OUTDIR/object /tmp/log.txt > /tmp/conversie-stdout.txt 2>/dev/null
  RESULT=$?
  if [ $RESULT -ne 0 ]; then
    echo DBK conversie ging mis, gebruik oude backup van `stat -c '%y' conversie-backup`
    echo Foutmeldingen:
    cat /tmp/conversie-stdout.txt
    cp $BACKUPDIR/features.json $OUTDIR
    cp -r $BACKUPDIR/object $OUTDIR
  else
    echo Conversie OK\; maken backup
    rm -rf $BACKUPDIR 2>/dev/null
    mkdir $BACKUPDIR
    cp $OUTDIR/features.json $BACKUPDIR
    cp -r $OUTDIR/object $BACKUPDIR
  fi  
```

In de else wordt dus de oude backup weggegooid, maar er is geen nieuwe data als de conversie mislukt is. Dat zorgde ervoor dat de voertuigviewer stuk ging.

**Comment by matthijsln** [comment]
Ik heb als workaround het if-statement aangepast dat niet alleen naar error code wordt gekeken maar ook of features.json bestaat:

```
  if [ $RESULT -ne 0 ] || ! [ -a $OUTDIR/features.json ]; then
```

**Comment by ankeur** [comment]
Ik heb een exit code toegevoegd. 

0=success
1=fail

**Comment by matthijsln** [comment]
Werkt, bedankt!
